### ISSUE TITLE
"Lax" interface definition for log level interferes with global functions

### ISSUE THREAD

**Issue by SvenRtbg** [rtheunissen/guzzle-log-middleware#10]
As per the documentation you can use `$middleware->setLogLevel(LogLevel::DEBUG);`. That constant is a string.

Later the log level is requested [here](https://github.com/rtheunissen/guzzle-log-middleware/blob/master/src/Logger.php#L193-L195), which checks if the value stored as the log level is callable.

Unfortunately if the string happens to also be a global function name, it is treated as callable, the global function will be called, and the result can be anything.

My example would be having a Laravel application that defines a global `info()` function, which accidentially is the same as the `info` log level.

The workaround is to use a closure that returns the constant log level string:
`$middleware->setLogLevel(function() { return LogLevel::INFO; });`

It would be better if there were two distinct methods that either accept a callable or a string, not both mixed in one method. If the pull request #9 for Guzzle 7 compatibility (with increased PHP requirement) is merged, would you consider having another pull request with this issue addressed?

**Comment by rtheunissen** [comment]
I've added a check specifically for `instanceof \Closure`, and tagged v2.0.0 since that breaks BC.

**Comment by SvenRtbg** [comment]
I'm not entirely sure what exactly happened, but maybe you missed pushing the master branch and only pushed tags. And I cannot see any hint of "\Closure" in the code shown as "v2.0.0". Please verify.

**Comment by rtheunissen** [comment]
Correct, sorry, I forget that `git push --tags` only pushes tags, not _also_ tags.
