### ISSUE TITLE
envoking logger

### ISSUE THREAD

**Issue by luebbert42** [rtheunissen/guzzle-log-middleware#2]
I tried to use the log-middleware like this

```
    $logger = new \Monolog\Logger("api_log");
    $logger->pushHandler(new MonologHandlerStreamHandler(app()->storagePath() . "/logs/api_log"));

    $middleware = new Concat\Http\Middleware\Logger($logger); /
    $stack = new HandlerStack();
    $stack->setHandler(new CurlHandler());
    $stack->push($middleware);

    $guzzleClient = new Client(
        [
            'handler' => $stack,
            // ... other stuff
        ]
```

This leads to a log, but guzzle posts (either form_params/multipart) do not work anymore, i.e. the posted data is not retrieved at the api endpoint. What am I doing wrong?

I am using guzzle 6.1

**Comment by rtheunissen** [comment]
What does the log show?

**Comment by luebbert42** [comment]
[2015-11-09 19:51:41] api_log.DEBUG: larantuka.fritz.box GuzzleHttp/6.1.0 curl/7.30.0 PHP/5.6.10 - [09/Nov/2015:19:51:41 +0000] "POST /contract HTTP/1.1" NULL NULL {"request":"[object](GuzzleHttp\Psr7\Request: {})","response":null,"reason":null} []

**Comment by rtheunissen** [comment]
Looks like the promise is being rejected without reason. Does the request work without the middleware?

**Comment by luebbert42** [comment]
yes. I removed the middleware and it's working again (and I also doublechecked with postman all the time). 

While debugging I replaced the api endpoint by a script reading 'php:://input' and parsing the query string with parse_str() - I noticed that the query string was set to "" while I used the middleware. I can try to set up a small demo  if you want to check my problem in detail. It's not urgent!

**Comment by rtheunissen** [comment]
Very strange. 

> I can try to set up a more small demo if you want to check my problem in detail.

A small demo would be very useful. :+1: 

Something else you could try is `var_dump` the value of `$options` in [`__invoke`](https://github.com/rtheunissen/guzzle-log-middleware/blob/master/src/Logger.php#L252)? "Logger.php" should be in your vendor directory and is quite a small file. Shouldn't be too difficult to determine at least at which point something is going wrong.

I'll try some requests myself in the meantime.

**Comment by rtheunissen** [comment]
@luebbert42 did you manage to figure it out or still stuck?

**Comment by luebbert42** [comment]
I tried to set up a small isolated example, yet I did not manage to reproduce it in this example while it is still not working in my app. I have to check this more in detail. I am closing this issue for the time being.
