### ISSUE TITLE
Having a debug function in the app will break the logger

### ISSUE THREAD

**Issue by Spir** [rtheunissen/guzzle-log-middleware#3]
Not sure what to think about this. I use the debugbar http://phpdebugbar.com/ and have a debug function to quickly add some data to the bar. I have set guzzle to use the log middleware with a level of \Psr\Log\LogLevel::DEBUG So when a log is being saved that if pass and then it screw : 

```
if (is_callable($this->logLevel)) {
    return call_user_func($this->logLevel, $response);
}
```

see: 
https://github.com/rtheunissen/guzzle-log-middleware/blob/master/src/Logger.php#L188

What you guys think of this? Should I namespace my debug function?

**Comment by rtheunissen** [comment]
> So when a log is being saved that if pass and then it screw

@Spir I'm not sure I understand what the issue is here. You're setting the log level to `DEBUG`, perhaps using `setLogLevel`, but where does your debug function come in? Are you trying to get something like this working?:

``` php
$middleware->setLogger(function($level, $message, $context) {
    // Call your debug function here
});
```

**Comment by Spir** [comment]
Sorry if I'm not clear, English is not my native tongue. What I'm saying is that I have a debug function in my app that is used for something that has no link to Guzzle/log. When I'm using Concat\Http\Middleware\Logger I set it to log DEBUG level log using : 

```
$middleware->setLogLevel(\Psr\Log\LogLevel::DEBUG);
```

So I'm using the lib correctly I guess. The problem is, the link I previously shared show that my debug function will be called : 

```
    if (is_callable($this->logLevel)) {
        return call_user_func($this->logLevel, $response);
    }
```

Because yes debug is a callable function! But it has nothing to do with that logger. My debug function return NULL. So When logger->log is called the LEVEL is set to NULL then I have an error from Monolog: "Method name must be a string".

Maybe just replace:

```
if (is_callable($this->logLevel))
```

by:

```
if ($this->logLevel instanceof \Closure)
```

Would do the trick!

**Comment by rtheunissen** [comment]
Oh right! That makes a lot of sense, I didn't think of that case. I'll fix it for you.

**Comment by Spir** [comment]
:+1: thanks

**Comment by rtheunissen** [comment]
@Spir I've been thinking about this issue and I'd like to preserve the ability to specify a `string` callable. I suggest that you either namespace your `debug` function, or use a closure instead:

``` php
$middleware->setLogLevel(function($response) {
    return \Psr\Log\LogLevel::DEBUG;
});
```

**Comment by Spir** [comment]
What do you think about checking the level there and throw an exception if not correct? Or should it be user responsibility (and then avoid extra checking code)? Just out of curiosity.

**Comment by rtheunissen** [comment]
It's not really about checking, it's to allow a way to determine the log level when a message is logged. For example, you might want to log 200 responses to `info`, but all 300+ responses to `warning`. Notice that the callable will receive the response as a parameter, which might help determine what the level should be. 

Unless I'm not quite understanding the question?
